dependencies:
  - name: redis
    version: "^24.1.0"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: "^18.2.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
