{{- if and .Values.postgresql.enabled .Values.postgresqlMigration.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-postgres-migration
  labels:
    {{- include "redash.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres-migration-rbac
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-postgres-migration
  labels:
    {{- include "redash.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres-migration-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-postgres-migration
subjects:
- kind: ServiceAccount
  name: {{ include "redash.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
